In [75]:
import torch 

input = torch.arange(16).view(4,4)
index = torch.LongTensor([[0,2,2,3]])
input

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [40]:
input.gather(dim=0,index = index)

tensor([[ 0,  9, 10, 15]])

In [76]:
torch.gather(input,1,index)

tensor([[0, 2, 2, 3]])

In [77]:
torch.gather(input,1,index.view(-1,1))

tensor([[ 0],
        [ 6],
        [10],
        [15]])

In [63]:
input = torch.tensor([[1, 2, 3], [4, 5, 6]])
index = torch.tensor([[0, 2, 1], [2, 0, 1]])
torch.gather(input, dim=1, index=index)

tensor([[1, 3, 2],
        [6, 4, 5]])

In [78]:
import torch

# 定义概率分布
probs = torch.tensor([0.1, 0.5, 0.4])
m = torch.distributions.Categorical(probs)

# 采样
sample = m.sample()
print(sample)

# 计算特定类别的概率
log_prob = m.log_prob(sample)
print(log_prob)


tensor(2)
tensor(-0.9163)


In [82]:
torch.log(torch.tensor(0.9))

tensor(-0.1054)

In [6]:
i = [1,2]
len(i)

2

In [10]:
li = list(range(10))
import random
random.choice(li)

6

In [3]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
di = {"q":1,
      "t":2}
list(di.keys()).index("3")

ValueError: '3' is not in list

In [24]:
d = [1,5,2,3,4,5]
for n,i in enumerate(d):
    print(n)

0
1
2
3
4
5


In [25]:
d.append([23])
d

[1, 5, 2, 3, 4, 5, [23]]

In [26]:
class MyClass:
    static_variable = 42  # 静态变量

    def __init__(self, value):
        self.instance_variable = value  # 实例变量

# 访问静态变量
print(MyClass.static_variable)

# 创建类的实例
obj1 = MyClass(10)
obj2 = MyClass(20)

# 修改静态变量
MyClass.static_variable = 100

# 查看修改后的静态变量
print(MyClass.static_variable)
print(obj1.static_variable)
print(obj2.static_variable)


42
100
100
100


In [30]:
s = [[1,"123"],[2,"456"]]
s = np.array(s)
s[:,0]

array(['1', '2'], dtype='<U11')

In [33]:
-5%4

3

In [35]:
l = [1,2,3,4,5]
l[1:]

[2, 3, 4, 5]