In [75]:
import torch 

input = torch.arange(16).view(4,4)
index = torch.LongTensor([[0,2,2,3]])
input

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [40]:
input.gather(dim=0,index = index)

tensor([[ 0,  9, 10, 15]])

In [76]:
torch.gather(input,1,index)

tensor([[0, 2, 2, 3]])

In [77]:
torch.gather(input,1,index.view(-1,1))

tensor([[ 0],
        [ 6],
        [10],
        [15]])

In [63]:
input = torch.tensor([[1, 2, 3], [4, 5, 6]])
index = torch.tensor([[0, 2, 1], [2, 0, 1]])
torch.gather(input, dim=1, index=index)

tensor([[1, 3, 2],
        [6, 4, 5]])

In [78]:
import torch

# 定义概率分布
probs = torch.tensor([0.1, 0.5, 0.4])
m = torch.distributions.Categorical(probs)

# 采样
sample = m.sample()
print(sample)

# 计算特定类别的概率
log_prob = m.log_prob(sample)
print(log_prob)


tensor(2)
tensor(-0.9163)


In [82]:
torch.log(torch.tensor(0.9))

tensor(-0.1054)